### Instructions
##### Concatenate Numerical and Categorical dataframes into one dataframe called data.
##### In this final lab, we will model our data. Import sklearn train_test_split and separate the data.
##### Separate X_train and X_test into numerical and categorical (X_train_cat , X_train_num , X_test_cat , X_test_num)
##### Use X_train_num to fit scalers. Transform BOTH X_train_num and X_test_num.
##### Encode the categorical variables X_train_cat and X_test_cat (See the hint below for encoding categorical data!!!)
##### Since the model will only accept numerical data, check and make sure that every column is numerical, if some are not, change it using encoding.
***********************************************
##### Hint for Categorical Variables
##### You should deal with the categorical variables as shown below (for ordinal encoding, dummy code has been provided as well):

##### Encoder Type	Column
##### One hot	state
##### Ordinal	coverage
##### Ordinal	employmentstatus
##### Ordinal	location code
##### One hot	marital status
##### One hot	policy type
##### One hot	policy
##### One hot	renew offercustomer_df
##### One hot	sales channel
##### One hot	vehicle class
##### Ordinal	vehicle size

##### Dummy code
##### data["coverage"] = data["coverage"].map({"Basic" : 0, "Extended" : 1, "Premium" : 2})
##### given that column "coverage" in the dataframe "data" has three categories:
##### "basic", "extended", and "premium" and values are to be represented in the same order.
******************************************************
##### Try a simple linear regression with all the data to see whether we are getting good results.
##### Great! Now define a function that takes a list of models and train (and tests) them so we can try a lot of them without repeating code.
##### Use the function to check LinearRegressor and KNeighborsRegressor.
##### You can check also the MLPRegressor for this task!
##### Check and discuss the results.

In [1]:
import pandas as pd
import numpy as np

file1 = pd.read_csv('numerical.csv')
file2 = pd.read_csv('categorical.csv')
file3 = pd.read_csv('numerical2.csv')
display(file1.columns)
display(file2.columns)
display(file3.columns)
display(file1.shape)
display(file2.shape)
display(file3.shape)
# -->they don't fit...can't concatinate...create numerical2...

Index(['Unnamed: 0', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'total_claim_amount'],
      dtype='object')

Index(['Unnamed: 0', 'state', 'response', 'coverage', 'education',
       'employmentstatus', 'gender', 'location_code', 'marital_status',
       'policy', 'renew_offer_type', 'sales_channel', 'vehicle_class',
       'vehicle_size'],
      dtype='object')

Index(['Unnamed: 0', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'total_claim_amount'],
      dtype='object')

(9099, 9)

(9134, 14)

(9134, 9)

In [2]:
# Concatenate Numerical and Categorical dataframes into one dataframe called data.
# total-claim-amount-->target

data = pd.concat([file2, file3], axis=1)
data = data.drop(['Unnamed: 0'], axis=1)
display(data)
display(data.columns)

state response  coverage education employmentstatus gender  \
0     Washington       No     Basic  Bachelor         Employed      F   
1        Arizona       No  Extended  Bachelor       Unemployed      F   
2         Nevada       No   Premium  Bachelor         Employed      F   
3     California       No     Basic  Bachelor       Unemployed      M   
4     Washington       No     Basic  Bachelor         Employed      M   
...          ...      ...       ...       ...              ...    ...   
9129  California       No     Basic  Bachelor         Employed      M   
9130  California      Yes  Extended   College         Employed      F   
9131  California       No  Extended  Bachelor       Unemployed      M   
9132  California       No  Extended   College         Employed      M   
9133  California       No  Extended   College       Unemployed      M   

     location_code marital_status     policy renew_offer_type  ...  \
0         Suburban        Married  Corporate           Offer1  ...   
1         Suburban         Single   Personal           Offer3  ...   
2         Suburban        Married   Personal           Offer1  ...   
3         Suburban        Married  Corporate           Offer1  ...   
4            Rural         Single   Personal           Offer1  ...   
...            ...            ...        ...              ...  ...   
9129         Urban        Married   Personal           Offer2  ...   
9130      Suburban       Divorced  Corporate           Offer1  ...   
9131      Suburban         Single  Corporate           Offer1  ...   
9132      Suburban        Married   Personal           Offer3  ...   
9133      Suburban         Single  Corporate           Offer4  ...   

      vehicle_class vehicle_size customer_lifetime_value  income  \
0      Two-Door Car      Medsize             2763.519279   56274   
1     Four-Door Car      Medsize             6979.535903       0   
2      Two-Door Car      Medsize            12887.431650   48767   
3      Expenciv Car      Medsize             7645.861827       0   
4     Four-Door Car      Medsize             2813.692575   43836   
...             ...          ...                     ...     ...   
9129  Four-Door Car      Medsize            23405.987980   71941   
9130  Four-Door Car      Medsize             3096.511217   21604   
9131  Four-Door Car      Medsize             8163.890428       0   
9132  Four-Door Car        Large             7524.442436   21941   
9133   Two-Door Car      Medsize             2611.836866       0   

      monthly_premium_auto  months_since_last_claim  \
0                       69                       32   
1                       94                       13   
2                      108                       18   
3                      106                       18   
4                       73                       12   
...                    ...                      ...   
9129                    73                       18   
9130                    79                       14   
9131                    85                        9   
9132                    96                       34   
9133                    77                        3   

      months_since_policy_inception  number_of_open_complaints  \
0                                 5                          0   
1                                42                          0   
2                                38                          0   
3                                65                          0   
4                                44                          0   
...                             ...                        ...   
9129                             89                          0   
9130                             28                          0   
9131                             37                          3   
9132                              3                          0   
9133                             90                          0   

      number_of_polici

Index(['state', 'response', 'coverage', 'education', 'employmentstatus',
       'gender', 'location_code', 'marital_status', 'policy',
       'renew_offer_type', 'sales_channel', 'vehicle_class', 'vehicle_size',
       'customer_lifetime_value', 'income', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies',
       'total_claim_amount'],
      dtype='object')

In [3]:
# Import sklearn train_test_split and separate the data.
X=data.drop(columns=['total_claim_amount'])
y=data['total_claim_amount']
# checking shape
print(X.shape)
print(y.shape)




(9134, 20)
(9134,)


In [4]:
# Separate X_train and X_test into numerical and categorical (X_train_cat , X_train_num , X_test_cat , X_test_num)
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test=tts(X, y, test_size=0.2, random_state=42)  # random state fixed sample

numericals_train = X_train.select_dtypes(np.number)
numericals_test = X_test.select_dtypes(np.number)
numericals_train.head()

customer_lifetime_value  income  monthly_premium_auto  \
5123              4768.955924   51144                    61   
7738              2827.559570       0                    79   
214               2912.892035   81097                    74   
8580              5138.244998   72264                    64   
7857              2610.369217   54737                    66   

      months_since_last_claim  months_since_policy_inception  \
5123                       28                             32   
7738                       30                             25   
214                         7                             67   
8580                        2                             66   
7857                        3                             86   

      number_of_open_complaints  number_of_policies  
5123                          1                   9  
7738                          0                   1  
214                           0                   1  
8580                          0                   9  
7857                          0                   1

In [5]:
# Use X_train_num to fit scalers. Transform BOTH X_train_num and X_test_num.
# is there a difference between scaler, transformer and encoder? translating don't help...
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(numericals_train)
numericals_train_scaled = transformer.transform(numericals_train)
numericals_test_scaled = transformer.transform(numericals_test)

display(numericals_train_scaled.shape)
display(numericals_test_scaled.shape)


(7307, 7)

(1827, 7)

## X_train_cat

In [6]:
X_train_cat = X_train.select_dtypes(object)

X_train_cat_1 = X_train_cat[['state', 'marital_status', 'policy', 'renew_offer_type', 'sales_channel', 'vehicle_class', 'employmentstatus', 'location_code']]
X_train_cat_2 = X_train_cat[['coverage', 'employmentstatus', 'location_code','vehicle_size', 'education']]

In [7]:
display(X_train_cat.shape)
display(X_train_cat_1.shape)
display(X_train_cat_2.shape)

(7307, 13)

(7307, 8)

(7307, 5)

## X_test_cat

In [8]:
X_test_cat = X_test.select_dtypes(object)

X_test_cat_1 = X_test_cat[['state', 'marital_status', 'policy', 'renew_offer_type', 'sales_channel', 'vehicle_class', 'employmentstatus', 'location_code']]
X_test_cat_2 = X_test_cat[['coverage', 'employmentstatus', 'location_code','vehicle_size', 'education']]

display(X_test_cat.shape)
display(X_test_cat_1.shape)
display(X_test_cat_2.shape)


(1827, 13)

(1827, 8)

(1827, 5)

## OneHotEncoder

In [9]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='error', drop='first').fit(X_train_cat_1)
X_train_cat_1_encoded = encoder.transform(X_train_cat_1).toarray()
X_test_cat_1_encoded = encoder.transform(X_test_cat_1).toarray()

## OrdinalEncoder

In [10]:
from sklearn.preprocessing import OrdinalEncoder

encoder2 = OrdinalEncoder()
X_train_cat_2_encoded = encoder2.fit_transform(X_train_cat_2)
X_test_cat_2_encoded = encoder2.fit_transform(X_test_cat_2)

In [11]:
# Since the model will only accept numerical data, check and make sure that every column 
# is numerical, if some are not, change it using encoding.
display(X_train_cat_1_encoded)
display(X_test_cat_2_encoded)
display(X_train_cat_2_encoded)
display(X_test_cat_2_encoded)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

array([[0., 0., 0., 1., 2.],
       [0., 0., 1., 1., 2.],
       [1., 0., 1., 2., 1.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 2., 1., 2., 2.],
       [0., 2., 1., 0., 1.]])

array([[0., 0., 2., 1., 0.],
       [1., 2., 1., 1., 1.],
       [0., 0., 1., 2., 1.],
       ...,
       [1., 2., 1., 1., 2.],
       [1., 2., 1., 1., 0.],
       [1., 0., 2., 1., 0.]])

array([[0., 0., 0., 1., 2.],
       [0., 0., 1., 1., 2.],
       [1., 0., 1., 2., 1.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 2., 1., 2., 2.],
       [0., 2., 1., 0., 1.]])

In [12]:
# Try a simple linear regression with all the data to see whether we are getting good results.

X_train = np.concatenate((X_train_cat_1_encoded, X_train_cat_2_encoded),axis=1)
X_test = np.concatenate((X_test_cat_1_encoded, X_test_cat_2_encoded),axis=1)

In [13]:
from sklearn.linear_model import LinearRegression as LinReg
linreg=LinReg()    # model
linreg.fit(X_train, y_train)   # model train
y_pred_linreg=linreg.predict(X_test)   # model prediction
print ('train R2: {} -- test R2: {}'.format(linreg.score(X_train, y_train),
                                            linreg.score(X_test, y_test)))
from sklearn.metrics import mean_squared_error as mse
train_mse=mse(linreg.predict(X_train), y_train)
test_mse=mse(linreg.predict(X_test), y_test)
print ('train MSE: {} -- test MSE: {}'.format(train_mse, test_mse))
print ('train RMSE: {} -- test RMSE: {}'.format(train_mse**.5, test_mse**.5))
from sklearn.metrics import mean_absolute_error as mae
train_mae=mae(linreg.predict(X_train), y_train)
test_mae=mae(linreg.predict(X_test), y_test)
print ('train MAE: {} -- test MAE: {}'.format(train_mse, test_mse))
def normalize(X):         # normalization function
    X_mean=X.mean(axis=0)
    X_std=X.std(axis=0)
    X_std[X_std==0]=1.0
    X=(X-X_mean)/X_std
    return X

train R2: 0.6586079633741764 -- test R2: 0.662580508909022
train MSE: 29206.650209070463 -- test MSE: 26828.574912236356
train RMSE: 170.89953250102957 -- test RMSE: 163.794306714966
train MAE: 29206.650209070463 -- test MAE: 26828.574912236356


In [14]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn import datasets
from sklearn import metrics
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error, r2_score

In [15]:
# Great! Now define a function that takes a list of models and train (and tests) them so we 
# can try a lot of them without repeating code.
# Use the function to check LinearRegressor and KNeighborsRegressor.
# You can check also the MLPRegressor for this task!

def r2_knn_mlp():
    
    #KNeigbhours
    k = int(input("Please type a value for n_neighbors=:"))
    knm = KNeighborsRegressor(n_neighbors=k)
    knm.fit(X_train, y_train)
    # Predictions on TRAIN data and score 
    kn_train_score = knm.score(X_train, y_train)
    # Predictions on TEST data and score
    kn_test_predictions = knm.predict(X_test)
    kn_test_score = knm.score(X_test, y_test)
    print("kn_test_score is: ", kn_test_score)
    
    # Linear Regression
    print("Linear Regression:")
    linreg=LinReg()    # model
    linreg.fit(X_train, y_train)   # model train
    y_pred_linreg=linreg.predict(X_test)   # model prediction
    print ('train R2: {} -- test R2: {}'.format(linreg.score(X_train, y_train),
                                                linreg.score(X_test, y_test)))
    
    #MLP Regressor

    # Fitting and training the model
    mlp = MLPRegressor(hidden_layer_sizes=(50, 50))
    mlp.fit(X_train, y_train)

    # Predictions on TEST data and score
    mlp_test_predictions = mlp.predict(X_test)
    mlp_test_score = r2_score(y_test,mlp_test_predictions)
    print("mlp_test_score is: ", mlp_test_score)

In [18]:
r2_knn_mlp()

Please type a value for n_neighbors=:10
kn_test_score is:  0.640458848548762
Linear Regression:
train R2: 0.6586079633741764 -- test R2: 0.662580508909022
mlp_test_score is:  0.7162836388495539


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [17]:
# mlp_test_score is best